// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRightClickShortcut(arg1) {
  return window['go']['main']['App']['AddRightClickShortcut'](arg1);
}

export function CheckAnalysisStatus() {
  return window['go']['main']['App']['CheckAnalysisStatus']();
}

export function ConfirmAnalysisSuccess() {
  return window['go']['main']['App']['ConfirmAnalysisSuccess']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetAnalysisResults() {
  return window['go']['main']['App']['GetAnalysisResults']();
}

export function GetFileInfo() {
  return window['go']['main']['App']['GetFileInfo']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OfferShortcut() {
  return window['go']['main']['App']['OfferShortcut']();
}

export function ShortcutExists() {
  return window['go']['main']['App']['ShortcutExists']();
}

export function StartFileScan() {
  return window['go']['main']['App']['StartFileScan']();
}
