// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAnalysisStatus():Promise<main.FunctionResult>;

export function ConfirmAnalysisSuccess():Promise<boolean>;

export function GetAnalysisResults():Promise<main.AnalysisResults>;

export function GetFileInfo():Promise<main.FileInfo>;

export function Greet(arg1:string):Promise<string>;

export function StartFileScan():Promise<main.FunctionResult>;
