// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRightClickShortcut(arg1) {
  return ObfuscatedCall(0, [arg1]);
}

export function CheckAnalysisStatus() {
  return ObfuscatedCall(1, []);
}

export function ConfirmAnalysisSuccess() {
  return ObfuscatedCall(2, []);
}

export function FinishAddingShortcut() {
  return ObfuscatedCall(3, []);
}

export function GetAPIKey() {
  return ObfuscatedCall(4, []);
}

export function GetAnalysisResults() {
  return ObfuscatedCall(5, []);
}

export function GetFileInfo() {
  return ObfuscatedCall(6, []);
}

export function GetStartupError() {
  return ObfuscatedCall(7, []);
}

export function Greet(arg1) {
  return ObfuscatedCall(8, [arg1]);
}

export function OfferShortcut() {
  return ObfuscatedCall(9, []);
}

export function ShortcutExists() {
  return ObfuscatedCall(10, []);
}

export function StartFileScan() {
  return ObfuscatedCall(11, []);
}
